require:
  - rubocop-rails
  - rubocop-performance

AllCops:
  Exclude:
    - 'Rakefile'
    - 'config.ru'
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'spec/**/*'
    - 'test/**/*'
    - 'bin/**/*'
    - 'lib/tasks/**/*'
    - 'Gemfile'
    - 'Guardfile'
    - 'Rakefile'
    - 'node_modules/**/*'
    - 'vendor/**/*'

  DisplayCopNames: true
  DisplayStyleGuide: true
  TargetRubyVersion: 3.1.2

Rails:
  Enabled: true

Layout/LineLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 9

Metrics/PerceivedComplexity:
  Max: 9

Naming/PredicateName:
  Enabled: false

Naming/MemoizedInstanceVariableName:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true

Lint/MissingSuper:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Style/HashSyntax:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Max: 25
